GET http://localhost:5000/authors

###
GET http://localhost:5000/authors/69d169ad8d8e9deb055dbbd9

###
POST http://localhost:5000/authors
Content-Type: application/json

{
    "firstName": "J.K. Grant",
    "lastName": "Rowling",
    "nationality": "British",
    "dob": "1965-07-31",
    "biography": "Author of the Harry Potter series."
}


###
PUT http://localhost:5000/authors/69da8a56f468b93284853f6c
Content-Type: application/json

{
    "firstName": "J.Kennedy Grant",
    "lastName": "Rowling",
    "nationality": "British",
    "dob": "1965-07-31",
    "biography": "Author of the Harry Potter series."
}


###
DELETE http://localhost:5000/authors/69da8a56f468b93284853f6c


###
GET http://localhost:5000/books


###
GET http://localhost:5000/books/69d1826437d6832b80e8c32d


###
POST http://localhost:5000/books
Content-Type: application/json

{
    "title": "The Lion and the Jewel",
    "authorId": "69d169ad8d8e9deb055dbbd9",
    "publishYear": 1963,
    "isbn": "9780199110834",
    "genre": "Drama",
    "copiesOwned": 3,
    "copiesAvailable": 3
}


###
PUT http://localhost:5000/books/69da8aa7f468b93284853f71
Content-Type: application/json

{
    "title": "The Lion and the Jewel 2",
    "authorId": "69d169ad8d8e9deb055dbbd9",
    "publishYear": 1975,
    "isbn": "9780199110867",
    "genre": "Drama",
    "copiesOwned": 7,
    "copiesAvailable": 7
}


###
DELETE http://localhost:5000/books/69da8aa7f468b93284853f71


###
GET http://localhost:5000/members

###
GET http://localhost:5000/members/69d651a2daeba36642f064c2


###
POST http://localhost:5000/members
Content-Type: application/json

{
"firstName": "Monroe",
"lastName": "Collins",
"phone": "07033334444",
"email": "maryjohnson@example.com",
"password": "123456"
}


###
PUT http://localhost:5000/members/69da70f6d3ac097a8c773ec0
Content-Type: application/json

{
"firstName": "Monroe Clare",
"lastName": "Collins",
"phone": "07033334444",
"email": "maryjohnson@example.com",
"password": "123456"
}


###
DELETE http://localhost:5000/members/69da70f6d3ac097a8c773ec0


###
GET http://localhost:5000/loans


###
POST http://localhost:5000/loans
Content-Type: application/json

  {
    "memberId": "645a1c5f3f1b2a1d4e8f1a22",
    "bookId": "645a1d8f3f1b2a1d4e8f1b35",
    "loanDate": "2026-03-20T12:00:00.000Z",
    "dueDate": "2026-04-03T12:00:00.000Z",
    "returnDate": "2026-04-02T14:00:00.000Z",
    "status": "returned"
  }


###
PUT http://localhost:5000/loans/69da6f8d5cc0a2ab3a5a62c1
Content-Type: application/json

  {
    "memberId": "645a1c5f3f1b2a1d4e8f1a22",
    "bookId": "69d1826437d6832b80e8c32d",
    "loanDate": "2026-03-20T12:00:00.000Z",
    "dueDate": "2026-04-03T12:00:00.000Z",
    "returnDate": "2026-04-25T14:00:00.000Z",
    "status": "overdue"
  }


###
DELETE http://localhost:5000/loans/69da6f8d5cc0a2ab3a5a62c1